import Head from 'next/head'
import Image from 'next/image'
import Landing from '../components/home/landing'
import NavBar from '../components/navbar/navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
       <NavBar/>
       <Landing/>
      </main>

    </div>
  )
}
